# 服务器相关配置
server:
  servlet:
    context-path: /monk
# spring相关配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: Yumc980219!!
    url: jdbc:mysql://localhost:3306/monk?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
  servlet:
    multipart:
      max-file-size: 100000000
      max-request-size: 100000000
# mybatis相关配置
mybatis:
  mapper-locations: classpath:com/baizhi/monk/mapper/*.xml
logging:
  level:
    #root: INFO
    com.baizhi: DEBUG